// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
// Bypasses TS6133. Allow declared but unused functions.
// @ts-ignore
function id(d: any[]): any { return d[0]; }

const stripSepAndFlatten = function<Item>(head : Item, tail : [any, Item][]) : Item[] {
    return [head, ...tail.map(([_, item]) => item)]
}

const deepJoin = function(data : any[] | string) : string {
  if (typeof data === "string") return data
  return data.map(deepJoin).join("")
}

interface NearleyToken {
  value: any;
  [key: string]: any;
};

interface NearleyLexer {
  reset: (chunk: string, info: any) => void;
  next: () => NearleyToken | undefined;
  save: () => any;
  formatError: (token: never) => string;
  has: (tokenType: string) => boolean;
};

interface NearleyRule {
  name: string;
  symbols: NearleySymbol[];
  postprocess?: (d: any[], loc?: number, reject?: {}) => any;
};

type NearleySymbol = string | { literal: any } | { test: (token: any) => boolean };

interface Grammar {
  Lexer: NearleyLexer | undefined;
  ParserRules: NearleyRule[];
  ParserStart: string;
};

const grammar: Grammar = {
  Lexer: undefined,
  ParserRules: [
    {"name": "main$string$1", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"x"}], "postprocess": (d) => d.join('')},
    {"name": "main", "symbols": ["_", "main$string$1", "_", {"literal":"{"}, "entries", {"literal":"}"}, "_"], "postprocess": (d) => d[4]},
    {"name": "entries$ebnf$1", "symbols": []},
    {"name": "entries$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"\\"}], "postprocess": (d) => d.join('')},
    {"name": "entries$ebnf$1$subexpression$1", "symbols": ["entries$ebnf$1$subexpression$1$string$1", "row"]},
    {"name": "entries$ebnf$1", "symbols": ["entries$ebnf$1", "entries$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "entries", "symbols": ["row", "entries$ebnf$1"], "postprocess": ([d, ds]) => stripSepAndFlatten(d, ds)},
    {"name": "row$ebnf$1", "symbols": []},
    {"name": "row$ebnf$1$subexpression$1", "symbols": [{"literal":"&"}, "cell"]},
    {"name": "row$ebnf$1", "symbols": ["row$ebnf$1", "row$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "row", "symbols": ["cell", "row$ebnf$1"], "postprocess": ([d, ds]) => stripSepAndFlatten(d, ds)},
    {"name": "cell$ebnf$1", "symbols": []},
    {"name": "cell$ebnf$1", "symbols": ["cell$ebnf$1", /[^&\\]/], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "cell", "symbols": ["cell$ebnf$1"], "postprocess": (d) : string => d[0].join("").trim()},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[\s]/], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": (d) => null},
    {"name": "letter", "symbols": [/[a-zA-Z]/]},
    {"name": "nonletter", "symbols": [/[^a-zA-Z]/]},
    {"name": "digit", "symbols": [/[0-9]/]},
    {"name": "space", "symbols": [{"literal":" "}]},
    {"name": "sign", "symbols": [/[+-]/]},
    {"name": "integer$ebnf$1", "symbols": ["sign"], "postprocess": id},
    {"name": "integer$ebnf$1", "symbols": [], "postprocess": () => null},
    {"name": "integer$ebnf$2", "symbols": ["digit"]},
    {"name": "integer$ebnf$2", "symbols": ["integer$ebnf$2", "digit"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "integer", "symbols": ["integer$ebnf$1", "integer$ebnf$2"]},
    {"name": "decimal$ebnf$1", "symbols": ["sign"], "postprocess": id},
    {"name": "decimal$ebnf$1", "symbols": [], "postprocess": () => null},
    {"name": "decimal$subexpression$1$ebnf$1", "symbols": ["digit"]},
    {"name": "decimal$subexpression$1$ebnf$1", "symbols": ["decimal$subexpression$1$ebnf$1", "digit"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "decimal$subexpression$1", "symbols": ["decimal$subexpression$1$ebnf$1"]},
    {"name": "decimal$subexpression$1$ebnf$2", "symbols": []},
    {"name": "decimal$subexpression$1$ebnf$2", "symbols": ["decimal$subexpression$1$ebnf$2", "digit"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "decimal$subexpression$1$ebnf$3", "symbols": []},
    {"name": "decimal$subexpression$1$ebnf$3", "symbols": ["decimal$subexpression$1$ebnf$3", "digit"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "decimal$subexpression$1", "symbols": ["decimal$subexpression$1$ebnf$2", {"literal":"."}, "decimal$subexpression$1$ebnf$3"]},
    {"name": "decimal", "symbols": ["decimal$ebnf$1", "decimal$subexpression$1"]},
    {"name": "unit$string$1", "symbols": [{"literal":"p"}, {"literal":"t"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$1"]},
    {"name": "unit$string$2", "symbols": [{"literal":"p"}, {"literal":"c"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$2"]},
    {"name": "unit$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$3"]},
    {"name": "unit$string$4", "symbols": [{"literal":"b"}, {"literal":"p"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$4"]},
    {"name": "unit$string$5", "symbols": [{"literal":"c"}, {"literal":"m"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$5"]},
    {"name": "unit$string$6", "symbols": [{"literal":"m"}, {"literal":"m"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$6"]},
    {"name": "unit$string$7", "symbols": [{"literal":"d"}, {"literal":"d"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$7"]},
    {"name": "unit$string$8", "symbols": [{"literal":"c"}, {"literal":"c"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$8"]},
    {"name": "unit$string$9", "symbols": [{"literal":"s"}, {"literal":"p"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$9"]},
    {"name": "unit$string$10", "symbols": [{"literal":"e"}, {"literal":"x"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$10"]},
    {"name": "unit$string$11", "symbols": [{"literal":"e"}, {"literal":"m"}], "postprocess": (d) => d.join('')},
    {"name": "unit", "symbols": ["unit$string$11"]},
    {"name": "active_character", "symbols": [/[~]/]},
    {"name": "control_sequence$ebnf$1", "symbols": ["letter"]},
    {"name": "control_sequence$ebnf$1", "symbols": ["control_sequence$ebnf$1", "letter"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "control_sequence", "symbols": [{"literal":"\\"}, "control_sequence$ebnf$1"]},
    {"name": "control_sequence", "symbols": [{"literal":"\\"}, "nonletter"]},
    {"name": "control_sequence", "symbols": ["active_character"]},
    {"name": "tex_code$ebnf$1", "symbols": []},
    {"name": "tex_code$ebnf$1$subexpression$1$ebnf$1", "symbols": [/[^{}\\]/]},
    {"name": "tex_code$ebnf$1$subexpression$1$ebnf$1", "symbols": ["tex_code$ebnf$1$subexpression$1$ebnf$1", /[^{}\\]/], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tex_code$ebnf$1$subexpression$1", "symbols": ["tex_code$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "tex_code$ebnf$1$subexpression$1", "symbols": [{"literal":"{"}, "tex_code", {"literal":"}"}]},
    {"name": "tex_code$ebnf$1$subexpression$1", "symbols": ["control_sequence"]},
    {"name": "tex_code$ebnf$1", "symbols": ["tex_code$ebnf$1", "tex_code$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tex_code", "symbols": ["tex_code$ebnf$1"], "postprocess": deepJoin},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$1$ebnf$1", "symbols": [/[^{}\\]/]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$1$ebnf$1", "symbols": ["tex_code_nonempty$ebnf$1$subexpression$1$ebnf$1", /[^{}\\]/], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$1", "symbols": ["tex_code_nonempty$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$1", "symbols": [{"literal":"{"}, "tex_code", {"literal":"}"}]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$1", "symbols": ["control_sequence"]},
    {"name": "tex_code_nonempty$ebnf$1", "symbols": ["tex_code_nonempty$ebnf$1$subexpression$1"]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$2$ebnf$1", "symbols": [/[^{}\\]/]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$2$ebnf$1", "symbols": ["tex_code_nonempty$ebnf$1$subexpression$2$ebnf$1", /[^{}\\]/], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$2", "symbols": ["tex_code_nonempty$ebnf$1$subexpression$2$ebnf$1"]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$2", "symbols": [{"literal":"{"}, "tex_code", {"literal":"}"}]},
    {"name": "tex_code_nonempty$ebnf$1$subexpression$2", "symbols": ["control_sequence"]},
    {"name": "tex_code_nonempty$ebnf$1", "symbols": ["tex_code_nonempty$ebnf$1", "tex_code_nonempty$ebnf$1$subexpression$2"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tex_code_nonempty", "symbols": ["tex_code_nonempty$ebnf$1"], "postprocess": deepJoin},
    {"name": "empty", "symbols": []},
    {"name": "id$ebnf$1", "symbols": ["letter"]},
    {"name": "id$ebnf$1", "symbols": ["id$ebnf$1", "letter"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "id", "symbols": ["id$ebnf$1"]},
    {"name": "dimen", "symbols": ["decimal", "unit"]},
    {"name": "factor", "symbols": ["decimal"]},
    {"name": "number", "symbols": ["integer"]},
    {"name": "text", "symbols": ["tex_code"]},
    {"name": "cs", "symbols": ["control_sequence"]},
    {"name": "xy$string$1", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}], "postprocess": (d) => d.join('')},
    {"name": "xy$string$2", "symbols": [{"literal":"\\"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"x"}, {"literal":"y"}], "postprocess": (d) => d.join('')},
    {"name": "xy", "symbols": ["xy$string$1", "pos", "decor", "xy$string$2"]},
    {"name": "pos$ebnf$1", "symbols": []},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"!"}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"."}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":","}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":";"}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":":"}, "coord"]},
    {"name": "pos$ebnf$1$subexpression$1$string$1", "symbols": [{"literal":":"}, {"literal":":"}], "postprocess": (d) => d.join('')},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": ["pos$ebnf$1$subexpression$1$string$1", "coord"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"*"}, "object"]},
    {"name": "pos$ebnf$1$subexpression$1$string$2", "symbols": [{"literal":"*"}, {"literal":"*"}], "postprocess": (d) => d.join('')},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": ["pos$ebnf$1$subexpression$1$string$2", "object"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"?"}, "place"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"@"}, "stacking"]},
    {"name": "pos$ebnf$1$subexpression$1", "symbols": [{"literal":"="}, "saving"]},
    {"name": "pos$ebnf$1", "symbols": ["pos$ebnf$1", "pos$ebnf$1$subexpression$1"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "pos", "symbols": ["coord", "pos$ebnf$1"]},
    {"name": "coord", "symbols": ["vector"]},
    {"name": "coord", "symbols": ["empty"]},
    {"name": "coord", "symbols": [{"literal":"c"}]},
    {"name": "coord", "symbols": [{"literal":"p"}]},
    {"name": "coord", "symbols": [{"literal":"x"}]},
    {"name": "coord", "symbols": [{"literal":"y"}]},
    {"name": "coord", "symbols": [{"literal":"s"}, "digit"]},
    {"name": "coord", "symbols": [{"literal":"s"}, {"literal":"{"}, "number", {"literal":"}"}]},
    {"name": "coord", "symbols": [{"literal":"\""}, "id", {"literal":"\""}]},
    {"name": "coord", "symbols": [{"literal":"{"}, "pos", "decor", {"literal":"}"}]},
    {"name": "vector", "symbols": [{"literal":"0"}]},
    {"name": "vector", "symbols": [{"literal":"<"}, "dimen", {"literal":","}, "dimen", {"literal":">"}]},
    {"name": "vector", "symbols": [{"literal":"<"}, "dimen", {"literal":">"}]},
    {"name": "vector", "symbols": [{"literal":"("}, "factor", {"literal":","}, "factor", {"literal":")"}]},
    {"name": "vector", "symbols": [{"literal":"a"}, {"literal":"("}, "number", {"literal":")"}]},
    {"name": "vector", "symbols": ["corner"]},
    {"name": "vector", "symbols": ["corner", {"literal":"("}, "factor", {"literal":")"}]},
    {"name": "vector", "symbols": [{"literal":"/"}, "direction", "dimen", {"literal":"/"}]},
    {"name": "corner", "symbols": [{"literal":"L"}]},
    {"name": "corner", "symbols": [{"literal":"R"}]},
    {"name": "corner", "symbols": [{"literal":"D"}]},
    {"name": "corner", "symbols": [{"literal":"U"}]},
    {"name": "corner$string$1", "symbols": [{"literal":"C"}, {"literal":"L"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$1"]},
    {"name": "corner$string$2", "symbols": [{"literal":"C"}, {"literal":"R"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$2"]},
    {"name": "corner$string$3", "symbols": [{"literal":"C"}, {"literal":"D"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$3"]},
    {"name": "corner$string$4", "symbols": [{"literal":"C"}, {"literal":"U"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$4"]},
    {"name": "corner", "symbols": [{"literal":"C"}]},
    {"name": "corner$string$5", "symbols": [{"literal":"L"}, {"literal":"D"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$5"]},
    {"name": "corner$string$6", "symbols": [{"literal":"R"}, {"literal":"D"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$6"]},
    {"name": "corner$string$7", "symbols": [{"literal":"L"}, {"literal":"U"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$7"]},
    {"name": "corner$string$8", "symbols": [{"literal":"R"}, {"literal":"U"}], "postprocess": (d) => d.join('')},
    {"name": "corner", "symbols": ["corner$string$8"]},
    {"name": "corner", "symbols": [{"literal":"E"}]},
    {"name": "corner", "symbols": [{"literal":"P"}]},
    {"name": "corner", "symbols": [{"literal":"A"}]},
    {"name": "place", "symbols": [{"literal":"<"}, "place"]},
    {"name": "place", "symbols": [{"literal":">"}, "place"]},
    {"name": "place", "symbols": [{"literal":"("}, "factor", {"literal":")"}, "place"]},
    {"name": "place", "symbols": ["slide"]},
    {"name": "place", "symbols": [{"literal":"!"}, {"literal":"{"}, "pos", {"literal":"}"}]},
    {"name": "slide", "symbols": [{"literal":"/"}, "dimen", {"literal":"/"}]},
    {"name": "stacking", "symbols": [{"literal":"+"}, "coord"]},
    {"name": "stacking", "symbols": [{"literal":"-"}, "coord"]},
    {"name": "stacking", "symbols": [{"literal":"="}, "coord"]},
    {"name": "stacking", "symbols": [{"literal":"@"}, "coord"]},
    {"name": "stacking", "symbols": [{"literal":"i"}]},
    {"name": "stacking", "symbols": [{"literal":"("}]},
    {"name": "stacking", "symbols": [{"literal":")"}]},
    {"name": "saving", "symbols": [{"literal":":"}, {"literal":"\""}, "id", {"literal":"\""}]},
    {"name": "saving", "symbols": ["coord", {"literal":"\""}, "id", {"literal":"\""}]},
    {"name": "saving", "symbols": [{"literal":"@"}, {"literal":"\""}, "id", {"literal":"\""}]},
    {"name": "object$ebnf$1", "symbols": []},
    {"name": "object$ebnf$1", "symbols": ["object$ebnf$1", "modifier"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "object", "symbols": ["object$ebnf$1", "objectbox"]},
    {"name": "objectbox", "symbols": [{"literal":"{"}, "text", {"literal":"}"}]},
    {"name": "objectbox", "symbols": ["library_object"]},
    {"name": "objectbox", "symbols": [{"literal":"@"}, "dir"]},
    {"name": "objectbox", "symbols": ["tex_box", {"literal":"{"}, "text", {"literal":"}"}]},
    {"name": "objectbox$string$1", "symbols": [{"literal":"\\"}, {"literal":"o"}, {"literal":"b"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": (d) => d.join('')},
    {"name": "objectbox", "symbols": ["objectbox$string$1", "object"]},
    {"name": "objectbox$string$2", "symbols": [{"literal":"\\"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "objectbox", "symbols": ["objectbox$string$2", {"literal":"{"}, "composite", {"literal":"}"}]},
    {"name": "objectbox$string$3", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"b"}, {"literal":"o"}, {"literal":"x"}], "postprocess": (d) => d.join('')},
    {"name": "objectbox", "symbols": ["objectbox$string$3", {"literal":"{"}, "pos", "decor", {"literal":"}"}]},
    {"name": "modifier", "symbols": [{"literal":"!"}, "vector"]},
    {"name": "modifier", "symbols": [{"literal":"!"}, "object"]},
    {"name": "modifier", "symbols": ["add_op", "size"]},
    {"name": "modifier", "symbols": [{"literal":"h"}]},
    {"name": "modifier", "symbols": [{"literal":"i"}]},
    {"name": "modifier", "symbols": [{"literal":"["}, "shape", {"literal":"]"}]},
    {"name": "modifier$string$1", "symbols": [{"literal":"["}, {"literal":"="}], "postprocess": (d) => d.join('')},
    {"name": "modifier", "symbols": ["modifier$string$1", "shape", {"literal":"]"}]},
    {"name": "modifier", "symbols": ["direction"]},
    {"name": "add_op", "symbols": [{"literal":"+"}]},
    {"name": "add_op", "symbols": [{"literal":"-"}]},
    {"name": "add_op", "symbols": [{"literal":"="}]},
    {"name": "add_op$string$1", "symbols": [{"literal":"+"}, {"literal":"="}], "postprocess": (d) => d.join('')},
    {"name": "add_op", "symbols": ["add_op$string$1"]},
    {"name": "add_op$string$2", "symbols": [{"literal":"-"}, {"literal":"="}], "postprocess": (d) => d.join('')},
    {"name": "add_op", "symbols": ["add_op$string$2"]},
    {"name": "size", "symbols": ["empty"]},
    {"name": "size", "symbols": ["vector"]},
    {"name": "direction", "symbols": ["diag"]},
    {"name": "direction", "symbols": [{"literal":"v"}, "vector"]},
    {"name": "direction$string$1", "symbols": [{"literal":"q"}, {"literal":"{"}], "postprocess": (d) => d.join('')},
    {"name": "direction", "symbols": ["direction$string$1", "pos", "decor", {"literal":"}"}]},
    {"name": "direction", "symbols": ["direction", {"literal":":"}, "vector"]},
    {"name": "direction", "symbols": ["direction", {"literal":"_"}]},
    {"name": "direction", "symbols": ["direction", {"literal":"^"}]},
    {"name": "diag", "symbols": [{"literal":"l"}]},
    {"name": "diag", "symbols": [{"literal":"r"}]},
    {"name": "diag", "symbols": [{"literal":"d"}]},
    {"name": "diag", "symbols": [{"literal":"u"}]},
    {"name": "diag$string$1", "symbols": [{"literal":"l"}, {"literal":"d"}], "postprocess": (d) => d.join('')},
    {"name": "diag", "symbols": ["diag$string$1"]},
    {"name": "diag$string$2", "symbols": [{"literal":"r"}, {"literal":"d"}], "postprocess": (d) => d.join('')},
    {"name": "diag", "symbols": ["diag$string$2"]},
    {"name": "diag$string$3", "symbols": [{"literal":"l"}, {"literal":"u"}], "postprocess": (d) => d.join('')},
    {"name": "diag", "symbols": ["diag$string$3"]},
    {"name": "diag$string$4", "symbols": [{"literal":"r"}, {"literal":"u"}], "postprocess": (d) => d.join('')},
    {"name": "diag", "symbols": ["diag$string$4"]},
    {"name": "composite", "symbols": ["object"]},
    {"name": "composite", "symbols": ["composite", {"literal":"*"}, "object"]},
    {"name": "decor$ebnf$1", "symbols": []},
    {"name": "decor$ebnf$1", "symbols": ["decor$ebnf$1", "command"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "decor", "symbols": ["decor$ebnf$1"]},
    {"name": "command$string$1", "symbols": [{"literal":"\\"}, {"literal":"s"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$1", "pos"]},
    {"name": "command$string$2", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$2"]},
    {"name": "command$string$3", "symbols": [{"literal":"\\"}, {"literal":"P"}, {"literal":"O"}, {"literal":"S"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$3", "pos"]},
    {"name": "command$string$4", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"P"}, {"literal":"O"}, {"literal":"S"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$4", {"literal":"{"}, "decor", {"literal":"}"}, "pos"]},
    {"name": "command$string$5", "symbols": [{"literal":"\\"}, {"literal":"d"}, {"literal":"r"}, {"literal":"o"}, {"literal":"p"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$5", "object"]},
    {"name": "command$string$6", "symbols": [{"literal":"\\"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$6", "object"]},
    {"name": "command$string$7", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"e"}, {"literal":"l"}, {"literal":"a"}, {"literal":"x"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$7"]},
    {"name": "command", "symbols": ["tex_commands"]},
    {"name": "command$string$8", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"b"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$8"]},
    {"name": "command$string$9", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$9"]},
    {"name": "command$string$10", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"e"}, {"literal":"t"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$10"]},
    {"name": "command$string$11", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"i"}, {"literal":"g"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$11", {"literal":"{"}, "pos", "decor", {"literal":"}"}]},
    {"name": "command$string$12", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$12", {"literal":"{"}, "pos", "decor", {"literal":"}"}]},
    {"name": "command$string$13", "symbols": [{"literal":"\\"}, {"literal":"x"}, {"literal":"y"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"o"}], "postprocess": (d) => d.join('')},
    {"name": "command", "symbols": ["command$string$13", {"literal":"{"}, "name", {"literal":"}"}, {"literal":"{"}, "pos", "decor", {"literal":"}"}]},
    {"name": "dir$subexpression$1$ebnf$1", "symbols": []},
    {"name": "dir$subexpression$1$ebnf$1", "symbols": ["dir$subexpression$1$ebnf$1", "tipchar"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "dir$subexpression$1", "symbols": ["dir$subexpression$1$ebnf$1"]},
    {"name": "dir$subexpression$1$ebnf$2", "symbols": []},
    {"name": "dir$subexpression$1$ebnf$2", "symbols": ["dir$subexpression$1$ebnf$2", "connchar"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "dir$subexpression$1", "symbols": ["dir$subexpression$1$ebnf$2"]},
    {"name": "dir", "symbols": ["variant", {"literal":"{"}, "dir$subexpression$1", {"literal":"}"}]},
    {"name": "variant", "symbols": ["empty"]},
    {"name": "variant", "symbols": [/[^_0123]/]},
    {"name": "radius", "symbols": ["empty"]},
    {"name": "radius", "symbols": ["vector"]},
    {"name": "cir", "symbols": ["empty"]},
    {"name": "cir", "symbols": ["diag", "orient", "diag"]},
    {"name": "orient", "symbols": [{"literal":"^"}]},
    {"name": "orient", "symbols": [{"literal":"_"}]},
    {"name": "PATH$string$1", "symbols": [{"literal":"\\"}, {"literal":"P"}, {"literal":"A"}, {"literal":"T"}, {"literal":"H"}], "postprocess": (d) => d.join('')},
    {"name": "PATH", "symbols": ["PATH$string$1", "path"]},
    {"name": "afterPATH$string$1", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"P"}, {"literal":"A"}, {"literal":"T"}, {"literal":"H"}], "postprocess": (d) => d.join('')},
    {"name": "afterPATH", "symbols": ["afterPATH$string$1", {"literal":"{"}, "decor", {"literal":"}"}, "path"]},
    {"name": "path", "symbols": [{"literal":"~"}, "action", {"literal":"{"}, "stuff", {"literal":"}"}, "path"]},
    {"name": "path", "symbols": [{"literal":"~"}, "which", {"literal":"{"}, "labels", {"literal":"}"}, "path"]},
    {"name": "path", "symbols": [{"literal":"~"}, {"literal":"{"}, "stuff", {"literal":"}"}, "path"]},
    {"name": "path", "symbols": [{"literal":"’"}, "segment", "path"]},
    {"name": "path", "symbols": [{"literal":"‘"}, "turn", "segment", "path"]},
    {"name": "path", "symbols": ["segment"]},
    {"name": "turn", "symbols": ["diag", "turnradius"]},
    {"name": "turn", "symbols": ["cir", "turnradius"]},
    {"name": "turnradius", "symbols": ["empty"]},
    {"name": "turnradius", "symbols": [{"literal":"/"}, "dimen"]},
    {"name": "segment", "symbols": ["path_pos", "slide", "labels"]},
    {"name": "slide", "symbols": ["empty"]},
    {"name": "slide", "symbols": [{"literal":"<"}, "dimen", {"literal":">"}]},
    {"name": "labels", "symbols": [{"literal":"^"}, "anchor", "it", "alias", "labels"]},
    {"name": "labels", "symbols": [{"literal":"_"}, "anchor", "it", "alias", "labels"]},
    {"name": "labels", "symbols": [{"literal":"|"}, "anchor", "it", "alias", "labels"]},
    {"name": "labels", "symbols": ["empty"]},
    {"name": "anchor", "symbols": [{"literal":"-"}, "anchor"]},
    {"name": "anchor", "symbols": ["place"]},
    {"name": "it", "symbols": ["digit"]},
    {"name": "it", "symbols": ["letter"]},
    {"name": "it", "symbols": [{"literal":"{"}, "text", {"literal":"}"}]},
    {"name": "it", "symbols": ["cs"]},
    {"name": "it", "symbols": [{"literal":"*"}, "object"]},
    {"name": "it", "symbols": [{"literal":"@"}, "dir"]},
    {"name": "it", "symbols": [{"literal":"["}, "shape", {"literal":"]"}, "it"]},
    {"name": "alias", "symbols": ["empty"]},
    {"name": "alias$string$1", "symbols": [{"literal":"="}, {"literal":"\""}], "postprocess": (d) => d.join('')},
    {"name": "alias", "symbols": ["alias$string$1", "id", {"literal":"\""}]},
    {"name": "action", "symbols": [{"literal":"="}]},
    {"name": "action", "symbols": [{"literal":"/"}]},
    {"name": "which", "symbols": [{"literal":"<"}]},
    {"name": "which", "symbols": [{"literal":">"}]},
    {"name": "which", "symbols": [{"literal":"="}]},
    {"name": "path_pos", "symbols": ["pos"]},
    {"name": "stuff", "symbols": ["pos", "decor"]},
    {"name": "ar$string$1", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"r"}], "postprocess": (d) => d.join('')},
    {"name": "ar", "symbols": ["ar$string$1", "arrow", "path"]},
    {"name": "arrow$ebnf$1", "symbols": []},
    {"name": "arrow$ebnf$1", "symbols": ["arrow$ebnf$1", "form"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "arrow", "symbols": ["arrow$ebnf$1"]},
    {"name": "form", "symbols": [{"literal":"@"}, "variant"]},
    {"name": "form", "symbols": [{"literal":"@"}, "variant", {"literal":"{"}, "tip", {"literal":"}"}]},
    {"name": "form", "symbols": [{"literal":"@"}, "variant", {"literal":"{"}, "tip", "conn", "tip", {"literal":"}"}]},
    {"name": "form", "symbols": [{"literal":"@"}, "connchar"]},
    {"name": "form$string$1", "symbols": [{"literal":"@"}, {"literal":"!"}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$1"]},
    {"name": "form$string$2", "symbols": [{"literal":"@"}, {"literal":"/"}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$2", "direction", "dist", {"literal":"/"}]},
    {"name": "form$string$3", "symbols": [{"literal":"@"}, {"literal":"("}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$3", "direction", {"literal":","}, "direction", {"literal":")"}]},
    {"name": "form$string$4", "symbols": [{"literal":"@"}, {"literal":"‘"}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$4", {"literal":"{"}, "control_point_list", {"literal":"}"}]},
    {"name": "form$string$5", "symbols": [{"literal":"@"}, {"literal":"["}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$5", "shape", {"literal":"]"}]},
    {"name": "form$string$6", "symbols": [{"literal":"@"}, {"literal":"*"}], "postprocess": (d) => d.join('')},
    {"name": "form$ebnf$1", "symbols": []},
    {"name": "form$ebnf$1", "symbols": ["form$ebnf$1", "modifier"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "form", "symbols": ["form$string$6", {"literal":"{"}, "form$ebnf$1", {"literal":"}"}]},
    {"name": "form$string$7", "symbols": [{"literal":"@"}, {"literal":"<"}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$7", "dimen", {"literal":">"}]},
    {"name": "form", "symbols": [{"literal":"|"}, "anchor", "it"]},
    {"name": "form", "symbols": [{"literal":"^"}, "anchor", "it"]},
    {"name": "form", "symbols": [{"literal":"_"}, "anchor", "it"]},
    {"name": "form$string$8", "symbols": [{"literal":"@"}, {"literal":"?"}], "postprocess": (d) => d.join('')},
    {"name": "form", "symbols": ["form$string$8"]},
    {"name": "tip$ebnf$1", "symbols": []},
    {"name": "tip$ebnf$1", "symbols": ["tip$ebnf$1", "tipchar"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "tip", "symbols": ["tip$ebnf$1"]},
    {"name": "tip", "symbols": ["dir"]},
    {"name": "tipchar", "symbols": [/[<>()|’‘+/]/]},
    {"name": "tipchar", "symbols": ["letter"]},
    {"name": "tipchar", "symbols": ["digit"]},
    {"name": "tipchar", "symbols": ["space"]},
    {"name": "conn$ebnf$1", "symbols": []},
    {"name": "conn$ebnf$1", "symbols": ["conn$ebnf$1", "connchar"], "postprocess": (d) => d[0].concat([d[1]])},
    {"name": "conn", "symbols": ["conn$ebnf$1"]},
    {"name": "conn", "symbols": ["dir"]},
    {"name": "connchar", "symbols": [/[-.~=:]/]},
    {"name": "dist", "symbols": ["dimen"]},
    {"name": "which", "symbols": [{"literal":"<"}]},
    {"name": "which", "symbols": [{"literal":">"}]},
    {"name": "which", "symbols": [{"literal":"="}]}
  ],
  ParserStart: "main",
};

export default grammar;
