name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        node: ["16"]
        include:
          - os: ubuntu-latest
            node: "16"
            coverage: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check generated grammars freshness
        run: |
          npm run grammars
          git diff --exit-code src/

      - name: Check code style
        run: npm run style:check

      - name: Run tests
        run: npm run test

      - name: Test and publish coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        if: ${{ matrix.coverage && github.ref == 'refs/heads/main' }}
        env:
          CC_TEST_REPORTER_ID: 7f1b527bfa83e18211d5d856c7468c51345ced860f008a2bbac6e11615ead4a6
        with:
          coverageCommand: npm run coverage
          coverageLocations: ${{ github.workspace }}/coverage/lcov.info:lcov
